### ISSUE TITLE
TypeError: Validation_args.__new__() missing 1 required positional argument: 'progress'

### ISSUE THREAD

**Issue by JozefAerts** [cdisc-org/cdisc-rules-engine#357]
CLI command: python core.py test -s sendig -v 3-1 -r D:\CDISC_Standards\CDISC_CORE\Metadata_rules_testing\SENDIG_266_rule.json --dataset-path D:\CDISC_Standards\CDISC_CORE\Metadata_rules_testing\SENDIG_266_negative_testdata_datasets.json
Error Stacktrace =
Traceback (most recent call last):
  File "D:\PycharmProjects\cdisc-rules-engine-main_2023-03-31\core.py", line 452, in <module>
    cli()
  File "C:\Users\Jozef\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Jozef\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Jozef\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Jozef\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Jozef\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Jozef\AppData\Local\Programs\Python\Python310\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "D:\PycharmProjects\cdisc-rules-engine-main_2023-03-31\core.py", line 374, in test
    test_rule(args)
  File "D:\PycharmProjects\cdisc-rules-engine-main_2023-03-31\scripts\test_rule.py", line 123, in test
    validation_args = Validation_args(
TypeError: Validation_args.__new__() missing 1 required positional argument: 'progress'
CORE version: main branch downloaded 2023-03-31
I attach the test files.

[SENDIG_266_negative_testdata_datasets.json.txt](https://github.com/cdisc-org/cdisc-rules-engine/files/11139999/SENDIG_266_negative_testdata_datasets.json.txt)
[SENDIG_266_rule.json.txt](https://github.com/cdisc-org/cdisc-rules-engine/files/11140004/SENDIG_266_rule.json.txt)

**Comment by nhaydel** [comment]
My current issue affects this code, so I will fix in my next PR

**Comment by nhaydel** [comment]
@JozefAerts this branch addresses the issue: https://github.com/cdisc-org/cdisc-rules-engine/pull/358

**Comment by nhaydel** [comment]
@JozefAerts the fix has been merged to main. Feel free to test again and close if possible

**Comment by JozefAerts** [comment]
Thanks! Will do so tomorrow! :-)

**Comment by JozefAerts** [comment]
Looks already a lot better ... still getting an error though:
[ERROR 2023-04-05 14:16:42,035 - console_logger.py:45] - Error occurred during validation. Error: 'NoneType' object has no attribute 'lower'. Error message: 'NoneType' object has no attribute 'lower'

**Comment by nhaydel** [comment]
> Looks already a lot better ... still getting an error though:
> 
> [ERROR 2023-04-05 14:16:42,035 - console_logger.py:45] - Error occurred during validation. Error: 'NoneType' object has no attribute 'lower'. Error message: 'NoneType' object has no attribute 'lower'

That is normal behavior if data does not conform to what an operator expects it will raise an error. Is that error causing any issues in generating a report?

**Comment by JozefAerts** [comment]
Ok! I see now, the report is correctly created!
Great work! It means that I can now start on some other SEND rules that use the CDISC Library.
So the issue can be closed imo.

**Comment by RamilCDISC** [comment]
I have tested the issue using the same files and commands for which @JozefAerts faced TypeError. The code is now fixed and generates a report successfully. Following screenshot shows the successful running of the command.
![image](https://user-images.githubusercontent.com/113539111/230196915-a8a84ff9-8efe-4b87-98be-cc330f4cf3c4.png)

The generated report is also attached for reference.

**Conclusion:** The issue in the code is fixed and can be closed successfully.

**Generated Report:** [CORE-Report-2023-04-06T00-45-40-sendig.xlsx](https://github.com/cdisc-org/cdisc-rules-engine/files/11162689/CORE-Report-2023-04-06T00-45-40-sendig.xlsx)

**Comment by RamilCDISC** [comment]
### Validation Summary

### Validation Methodology:
The validation process incorporated rigorous testing methodologies to ensure the accuracy and reliability of the system. This included:
**Manual Testing:**
A manual testing was done using the same dataset and rule file for which @jozefAerts got the error. This was to ensure that the bug has been fixed. After that 2 more different rule and datasets were used to validate the proper running of the function.

**Regression Testing:**
Regression tests were run to validate that the changes did not affect any functionality of the overall system.


### Test Cases:
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-624023f3-7fff-ab61-14a0-e8755b4bb449"><div dir="ltr" style="margin-left:0pt;" align="left">

Test Case Description | Function Name | Expected Result | Result
-- | -- | -- | --
Test if the error is regenerated using the same dataset and rule file | test | Expected result: Error is not generated | Passed
Test if error is generated using some other rule and dataset file | test | Expected result: Error is not generated | Passed

</div></b>### Test Execution:
The Tests were run by executing the manual test. Following command was run for execution of tests:
python -m core test -s sdtmig -v 3.4 -r path/to/rule/file -dp path/to /datasetfile

The regression tests were executed using the following command:
Python -m pytest test_cli.py


### Results:
After successful running of manual and regression tests and careful validation, the issue was found to be good to close as the Acceptance criteria was fulfilled and all validations passed.
### Deviations and Non-conformances:
No deviations or non-conformances were observed.
### Summary of Findings:
**Test Results:** All tests conducted during the validation process passed successfully, indicating that the system functions as intended and meets the specified requirements. The tests covered various scenarios and edge cases, providing confidence in the system's reliability and correctness.
**Unit Regression**: The unit regression tests were executed, and no regressions or issues were identified. This indicates that the changes made during the development or modification of the system did not introduce any unintended side effects or break existing functionality.
**Code Reviews**: The code reviews conducted by both development and QA teams were completed, and no major issues or concerns were identified. The code adheres to coding standards and best practices, demonstrating good code quality, readability, and maintainability.
